# Project info
project: 'DEEPWAVE'  # 20140606
fltno: 'RF01'

# Port setting
udp_send_port: 32106  # fron viewer to MTP
udp_read_port: 32107  # from MTP to viewer
iwg1_port: 7071       # IWG1 packets from GV

# Config for current MTP setup
NUM_SCAN_ANGLES: 10   # Number of scan angles being read
NUM_CHANNELS: 3       # Number of channels being read
LOC_HOR: 5            # Scan Angle Index of horizontal scan. Index starts at 0

# Gain equation constants
GeqnMin: 10           # Minimum acceptable gain
GeqnMax: 40           # Maximum acceptable gain

# The constants GOF and GEC don't change in real-time mode. To initialize
# a new project, copy the latest values from the previous project.
# From DEEPWAVE RF01 post-processing (so can compare with nimbus and
# VB6 results to confirm these calcs are OK)
GOF: 40.6             # Gain offset to subtract from Mixer Temperature Counts
GEC: [[19.87, 0.1], [23.1, 0.1], [26.05, 0.1]]  # Per channel slope, intercept

# From CSET
# GOF: 42
# GEC: [[19.43, 0.2], [22.44, 0.2],[25.29, 0.2]]

# Location of ascii_parms file
ascii_parms: 'config/ascii_parms'

# Location of RCF dir
RCFdir: 'config/RCF'
