###############################################################################
# This is the configuration file required to run the MTPviewer application. The
# format of this file is YAML. What this means to you is that each
# configuration variable is stored on a single line as a key, followed by a
# colon, and then a value:
#    key: value
# where the value is in single quotes if it is a string, or not if it is a
# number. GEC is the one exception. It is an array with three slope intercept
# pairs so the value is in nested square brackets:
# [[CH1slope, CH1intercpt], [CH2slope, CH2intercpt], [CH3slope, CH3intercpt]]
#
# Written in YAML (https://yaml.org)
#
# COPYRIGHT:   University Corporation for Atmospheric Research, 2020
###############################################################################

# Project info
project: 'DEEPWAVE'  # 20140606
fltno: 'RF01'

# Port setting
udp_send_port: 32106  # fron viewer to MTP
udp_read_port: 32107  # from MTP to viewer
iwg1_port: 7071       # IWG1 packets from GV

# Current MTP scan setup
NUM_SCAN_ANGLES: 10   # Number of scan angles being read
NUM_CHANNELS: 3       # Number of channels being read
LOC_HOR: 5            # Scan Angle Index of horizontal scan. Index starts at 0

# Gain equation constants
GeqnMin: 10           # Minimum acceptable gain
GeqnMax: 40           # Maximum acceptable gain

###############################################################################
# The constants GOF and GEC don't change in real-time mode. To initialize
# a new project, copy the latest values from the previous project.
###############################################################################
# For testing, use the constants from DEEPWAVE RF01 post-processing (so can
# compare with nimbus and VB6 results to confirm these calcs are OK)
GOF: 40.6             # Gain offset to subtract from Mixer Temperature Counts
GEC: [[19.87, 0.1], [23.1, 0.1], [26.05, 0.1]]  # Per channel slope, intercept

# From CSET
# GOF: 42
# GEC: [[19.43, 0.2], [22.44, 0.2],[25.29, 0.2]]

###############################################################################
# Locations of required files. Dir must either be absolute, or relative to dir
# you are running MTPviewer from. During testing, run:
#     python3 src/MTPviewer.py
# and use paths relative to the src dir, i.e. beginning with config. During
# deployment, copy the config dir to your project dir and use absolute paths
# here.
###############################################################################
# Location of ascii_parms file
ascii_parms: 'config/ascii_parms'

# Location of RCF dir
RCFdir: 'config/RCF'
