# Project info
project: 'DEEPWAVE'  # 20140606
fltno: 'RF01'

# Port setting
udp_send_port: 32106  # fron viewer to MTP
udp_read_port: 32107  # from MTP to viewer
iwg1_port: 7071       # IWG1 packets from GV

# Config for current MTP setup
NUM_SCAN_ANGLES: 10   # Number of scan angles being read
NUM_CHANNELS: 3       # Number of channels being read

# Location of ascii_parms file
ascii_parms: 'config/ascii_parms'

# Location of RCF dir
RCFdir: 'config/RCF'
